### ISSUE TITLE
Inicijalna postavka baze

### ISSUE THREAD

**Issue by andrejanesic** [RAF-SI-2022/Banka-2-Backend#21]
- Pregledati spec. da li postoji jos neki korisnik osim admin i user-a
- Kreirati model baze za te korisnike
- Izgenerisati kod za bazu
- Izgenerisati klasni dijagram
- Hibernate/JPA, opciono Flyway
- Sto jednostavnija implementacija radi lakseg odrzavanja

**Comment by DusanBrankovic** [comment]
Predlog: Koristiti kombinaciju _Flyway_ (za verzionisanje baze) + _Hibernate_ (za validaciju modela i baze) kako bismo lakše vodili računa o izmenama koje se vrše nad bazom.

Ukratko:

Flyway omogućava pisanje migracionih skripti preko kojih bi se sve izmene nad bazom radile.
On kreira tabelu `flyway_schema_history` koja čuva informacije o tim izmenama.

Hibernate ne bi imao permisiju da menja bazu već da samo validira konzistentnost klasa modela sa onim šta je u bazi.

U videu sam pokazao pisanje prve dve migracione skripte:

 1. kreiranje tabele `users`
 2. brisanje kolone `password`

Videćete da se Hibernate buni kada se izvrši druga skripta, jer u bazi više ne postoji ta kolona, a klasa modela to zahteva.

Link ka kratkoj demonstraciji: https://www.youtube.com/watch?v=2wxLkku4x2E

**Comment by andrejanesic** [comment]
@DusanBrankovic ovo nije lose, mene samo brine sto ovde direktno moramo da kucamo SQL... ne znam koliko ce se ljudi snaci sa time.

Takodje, jel postoji mogucnost da se izgenerisu modeli (Java kod) iz trenutnog stanja baze?

**Comment by DusanBrankovic** [comment]
Slažem se da je to može biti problem, ali ne verujem da će baza biti nešto mnogo komplikovanija kasnije. Svakako ćemo dodavati malo po malo.

Flyway samo vodi računa o verzionisanju, ne znam da li postoji tako nešto.

**Comment by andrejanesic** [comment]
@DusanBrankovic malo sam istrazio o ovome, mislim da treba da nastavimo sa Flyway bas kao sto si poceo.

U vezi toga, ovde ima dobro objasnjeno da Hibernate zapravo nema mogucnost migracije i da bismo prakticno morali da pisemo sami SQL skripte bez "nativne" podrske framework-a za to: https://stackoverflow.com/questions/3923574/jpa-hibernate-support-for-migration
@ntadicrn4419 @lbrcic4219rn ^pogledajte ovo, mislim da je @DusanBrankovic u pravu da ovde koristimo Flyway.

Sto se tice ostatka, @DusanBrankovic jel si ukomponovao i Hibernate u projekat? Predpostavljam da jesi ali cisto da potvrdim.

**Comment by DusanBrankovic** [comment]
Forkovao sam kod sebe Nikolin fork i ubacio Flyway. Konfigurisao sam sve kao i u svom demo projektu i izgleda kao da je sve okej.

Da bi aplikacija mogla da se pokrene mora da postoji inicijalna migracija. Ona bi mogla da kreira tabelu `users` po specifikaciji projekta.

**Comment by andrejanesic** [comment]
@DusanBrankovic gotovo, hvala. Ako bi mogao da azuriras dokumentaciju vezanu za bazu trenutno, upotrebu Flyway, itd.:
https://docs.google.com/document/d/1Wm4-tTII1BuZra9huSQd2jeqTKXlBxOtUVjOl6jY2-Y/edit#
