### ISSUE TITLE
Implementirati JWT, autentifikacija i autorizacija

### ISSUE THREAD

**Issue by andrejanesic** [RAF-SI-2022/Banka-2-Backend#23]
#TODO @lbrcic4219rn opisati task, dodati assignee

**Comment by lbrcic4219rn** [comment]
Neophodno je kreirati JWT util kalsu koja ce: 

1. Kreirati tokene
2. Proveravati validnost tiketa

Pored toka neophodno je napraviti i jwt filter koji ce naslediti OncePerRequestFilter i proveravati da li svaki dolazeci request ima token

**Comment by andrejanesic** [comment]
Primeri koda:
https://github.com/lbrcic4219rn/BEdomaci3
<https://mailtrack.io/trace/link/e712736fb1e5589d6b13d521f4d018be3cabc74c?url=https%3A%2F%2Fgithub.com%2Flbrcic4219rn%2FBEdomaci3&userId=5089678&signature=33c5a59bb8967c73>
https://github.com/ljeremic4019rn/NWP_domaci3-projekat_back
<https://mailtrack.io/trace/link/dc98b33a9015dd24a8fa1cfa47d29b2fbe7b71b4?url=https%3A%2F%2Fgithub.com%2Fljeremic4019rn%2FNWP_domaci3-projekat_back&userId=5089678&signature=f1be98e28988a460>

**Comment by andrejanesic** [comment]
@DusanGligorijevic potrebno ovde odraditi i autorizaciju
