### ISSUE TITLE
Validacija polja prilikom poziva

### ISSUE THREAD

**Issue by lbrcic4219rn** [RAF-SI-2022/Banka-2-Backend#31]
Neophodne je validirati svakog polja klase i proveriti da li se odgovarajuce poruke dobijaju prilikom poziva za kreiranjae i azuriranje korisnika. Validaciju odraditi pomocu anotacija u model klasi

**Comment by andrejanesic** [comment]
@pstevanovic1219rn vracam ovo u Todo, molim te da sutra popravis jer nam je sutra deadline za prvi sprint. Takodje komituj one testove slobodno

@lbrcic4219rn

**Comment by andrejanesic** [comment]
@pstevanovic1219rn @lbrcic4219rn jel mogu sada da oznacim ovo kao Closed?

**Comment by lbrcic4219rn** [comment]
@andrejanesic Moze!
