### ISSUE TITLE
Kontroleri, servisi, login, register

### ISSUE THREAD

**Issue by ntadicrn4419** [RAF-SI-2022/Banka-2-Backend#33]
Implementirati kontroler klasu za korisnika - UserController.
Implementirati kontroler klasu za logovanje korisnika - AuthentificationController
Implementirati servis klasu za korisnika - UserService.

Implementirati login operaciju (u AuthentificationContrller klasi) i register opearaciju (u UserController klasi).

U UserController napraviti entpoint-ove(rute) za osnovne CRUD operacije:
1.create - registrovanje user-a
2.read - get-ovanje user-a po id i getovanje svih user-a
3.update - za sada ne treba
4.delete brisanje user-a

**Comment by andrejanesic** [comment]
@ntadicrn4419 da li mozes da pogledas PR? Meni deluje ok, a cini mi se da je kolega zapoceo i autentifikaciju/autorizaciju
https://github.com/RAF-SI-2022/Banka-2-Backend/pull/34
