### ISSUE TITLE
Mail service za password reset

### ISSUE THREAD

**Issue by ljeremic4019rn** [RAF-SI-2022/Banka-2-Backend#41]
- Mail servis koji sluzi da user resetuje password u slucaju da zaboravi
- Sto generalnije resenje, da mozemo da ga koristimo za razne transakcione mejlove, ne samo ovaj (npr u buducnosti kada je order ispunjen da mozemo da posaljemo mejl)

**Comment by andrejanesic** [comment]
@ljeremic4019rn jel bi mogao sa Brnabicem da pocnes i ovo?

**Comment by DusanBrankovic** [comment]
Mogu da pomognem ako bude potrebna pomoć, skoro sam koristio javax.mail

**Comment by andrejanesic** [comment]
@ljeremic4019rn sori slucajno sam te tagovao ovde u komentaru gore

@lbrcic4219rn vidi ovo

**Comment by andrejanesic** [comment]
@lbrcic4219rn @ljeremic4019rn kako napreduje ovo i da li treba pomoc

**Comment by lbrcic4219rn** [comment]
@andrejanesic Gotovo!
