### ISSUE TITLE
Pri pokretanju docker-a automatizovati dodavanje admina i permisija u bazu

### ISSUE THREAD

**Issue by ntadicrn4419** [RAF-SI-2022/Banka-2-Backend#44]
Trenutno kada se pokrene docker, baza je prazna. Admin mora rucno da se doda u tabelu users, permisije moraju rucno da se dodaju u tabelu permissions, takodje rucno mora da se doda red u tabeli users_permissions (admin_id, permissions_id). Bilo bi dobro pri pokretanju docker-a da se taj proces automatizuje. Npr moguca ideja: imati neki folder "dumps" u kome postoji json fajl za svaku tabelu: users.json, permissions.json, users_permissions.json u kojima se nalazi podaci koje treba ubaciti u bazu pri pokretanju.

**Comment by andrejanesic** [comment]
Hvala @ntadicrn4419.
