### ISSUE TITLE
Napraviti dijagram baze

### ISSUE THREAD

**Issue by ljeremic4019rn** [RAF-SI-2022/Banka-2-Backend#51]

**Comment by DusanBrankovic** [comment]
Dogovoreno, generisaću čim se merge-uje mail servis deo projekta na sprint-1 pošto će postojati nova tabela.

**Comment by andrejanesic** [comment]
@andrejanesic radim na ovome upravo

**Comment by andrejanesic** [comment]
Jel moze ovako: [users (1).pdf](https://github.com/RAF-SI-2022/Banka-2-Backend/files/10963094/users.1.pdf)

**Comment by DusanBrankovic** [comment]
Okej je. Daj mi samo desetak minuta, odradiću preko DBeavera. 
Zeza me docker desktop nešto.

**Comment by andrejanesic** [comment]
@ljeremic4019rn @DusanBrankovic samo kad zavrsite oznacite ovo kao closed

**Comment by DusanBrankovic** [comment]
![image](https://user-images.githubusercontent.com/72136195/224867151-cb6a6b81-6c0f-44df-9761-57d2fc09daab.png)
